# Generated by Django 5.1.4 on 2024-12-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(null=True, upload_to="resumes/"),
        ),
    ]
