# Generated by Django 5.1.4 on 2024-12-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_userprofile_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
