# Generated by Django 5.1.4 on 2025-01-27 08:40

import django.core.validators
import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_job_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentprogress",
            name="last_position",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.CharField(
                choices=[
                    ("Business", "Business"),
                    ("Information Technology", "It"),
                    ("Banking", "Banking"),
                    ("Education/Training", "Education"),
                    ("Telecommunication", "Telecommunication"),
                    ("Others", "Others"),
                ],
                default="Business",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="lastDate",
            field=models.DateTimeField(default=job.models.return_date_time),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
        ),
    ]
